= System Architecture

== Current state

From user perspective dbOpera is transactional system, to which we can load data from file, get reports and do some actions on GUI.
On back-end side we have full interactions between, and what is worth noting all of them change business data.

.Overview of dbOpera components, and relations between them.
[ditaa, "{plantUMLDir}hl_overview_now", png]
----
                                 +----------------------+                                             +----------------------+
                                 |cFCC                  | <=----------------------------------------> |cCEF                  |
                                 |    other systems     |                                             |                      |
                                 |                      |                                             | BATCH processing     |
                                 |                      |                                             |                      |
                                 |                      |        +---------------------+              |                      |
                                 |                      |        | {s}                 |              |                      |
                                 +--+------------+------+        |                     |              +----------------------+
                                    ^            ^               |        Business     |                     ^            ^
                                    :            :               |        Data         |                     :            :
                                    |            |               |                     |                     |            |
                                    |            +-------------->|                     |<--------------------+            |
                                    |                            |                     |                                  |
                                    |                            |                     |                                  |
                                    |                            |                     |                                  |
                                    |                            |                     |                                  |
                                    |                            |                     |                                  |
                                    |                            |                     |                                  |
                                    |                            |              cEEE   |                                  |
+----------------------------+      |                            +---------------------+                                  |         +------------------------------+
:                            |      |                                       ^                                             |         :                              |
|                            |      |                                       |                                             |         |                              |
|  Uploads           +----+  |      |                                       |                                             |         |       +----+     Reports     |
|                    |    |  |      |                                       v                                             |         |       |    |                 |
|                    | {d}|  |      |                            +----------------------+                                 |         |       | {d}|                 |
|                    +----+  |      |                            |{io}                  |                                 |         |       +----+                 |
|                            |      +--------------------------> |  transaction         | <-------------------------------+         |                              |
|                    +----+  |                                   |                      |                                           |       +----+                 |
|                    |    |  |                                   |  process system      |                                           |       |    |                 |
|                    | {d}|  |                                   |                      |                                           |       | {d}|                 |
|                    +----+  |  +------------------------------> |                cCCF  | +-------------------------------------->  |       +----+                 |
|                            |                                   +----------------------+                                           |                              |
|                    +----+  |                                                                                                      |       +----+                 |
|                    |    |  |                                                                                                      |       |    |                 |
|                    | {d}|  |                                                                                                      |       | {d}|                 |
|                    +----+  |                                                                                                      |       +----+                 |
|                      cCCF  |                                                                                                      |                              |
+----------------------------+                                                                                                      |                              |
                                                                                                                                    +------------------------------+
----

Loose approach to control and minimal amount of constraints makes environment very flexible.
It has benefits, especially if we want to have quick results, and we do not care in long term perspective. 

This kind of architecture has also some disadvantages.
Mix of huge rotation in development team in dbOpera area, lack of system architecture and focus on short perspective goals provide to unstructured and difficult to maintain source code.

== One of the possible ways

To keep similar functionalities all main components must remain, but to increase architectural order, character each of them should be changed.
Role of each components must be reduced to area dedicated to them, while well documented consistent and stable interfaces should ensure isolation on Business Data.

In connection with the above, and follow the rule to effective utilize current resources quite natural is move all reporting functionalities into already created COGNOS tool.
A natural consequence of this step is enrich ETL process in DWH by Business Data which are necessary for reporting.
Another step back is change transactional part of system, should be reduced, it mean transformed into component responsible for interaction with user and preparing input data for ETL system.

.Overview of dbOpera after change.
[ditaa, "{plantUMLDir}hl_overview_after", png]
----
                                                                +----------------------+
                                                                |                      |
                                                                |    other systems     |
                                                                |                      |
                                                                |                      |
                                                                |                      |
                                                                |                 cFCC |
                                                                +-----------+----------+
                                                                            |
                                                                            |
                                                               +------------|--------------------------------------------------------------------------------------+
                                                               |            |                                                                                      |
                                                               |            V                                                                                DWH   |
+----------------------------+                                 |   +-----------------+ +-------------------+  +-------------------------------------+              |
:                            |                                 |   |                 | |                   |  |                                     |              |
+                            |                                 |   |                 | |                   |  |             +--------------------+  |              |
|  Uploads           +----+  |                                 |   |  Data           | |   ETL             |  | COGNOS      :                    |  |              |
|                    |    |  |                                 |   |  Sources        | |                   |  | Reporting   + +----+     Reports |  |              |
|                    | {d}|  |     +----------------------+    |   |                 | |       +---------+ |  |             | |    |             |  |              |
|                    +----+  |     |{io}                  |    |   |   +--+          | |       |{s}      | |  |             | | {d}|             |  |              |
|                            |     |  transaction         |    |   |   |  +------------------->+ Business| |  |             | +----+             |  |              |
|                    +----+  +---> |                      +------> |   +--+          | |       | Data    | |  |             |                    |  |              |
|                    |    |  |     |  process system      |    |   |                 | |       |         | |  |             | +----+             |  |              |
|                    | {d}|  |     |                      |    |   |   +--+          | |       |         | |  |             | |    |             |  |              |
|                    +----+  |     |               cCCF   |    |   |   |  +------------------->+         +----------------> | | {d}|             |  |              |
|                            |     +----------------------+    |   |   +--+          | |       |         | |  |             | +----+             |  |              |
|                    +----+  |                                 |   |                 | |       |         | |  |             |                    |  |              |
|                    |    |  |                                 |   |   +--+          | |       |         | |  |             | +----+             |  |              |
|                    | {d}|  |                                 |   |   |  +------------------->+     cEEE| |  |             | |    |             |  |              |
|                    +----+  |                                 |   |   +--+          | |       +---------+ |  |             | | {d}|             |  |              |
|                            |                                 |   |                 | |                   |  |             | +----+             |  |              |
+----------------------------+                                 |   |                 | |              cCEF |  |             +--------------------+  |              |
                                                               |   +-----------------+ +-------------------+  +-------------------------------------+              |
                                                               |                                                                                                   |
                                                               |                                                                                                   |
                                                               |                                                                                                   |
                                                               +---------------------------------------------------------------------------------------------------+
----
